server:
    port: 0
spring:
    application:
        name: menu-service
    cloud:
        consul:
            discovery:
                health-check-critical-timeout: 1s
                health-check-interval: 3s
                health-check-timeout: 1s
                instanceId: ${spring.application.name}:${random.value}
                tags: ${spring.application.name}
            host: ${CONSUL_HOST:localhost}
            port: 8500
    profiles:
        active: memory
